### PR TITLE
Revert "Added support for dot-separated miner username(partially) + S…

### PR DESCRIPTION
**Pull request by vagabondan**
Reverts vagabondan/CoiniumServ#10
There some issues that need to be clarified

### CODE REVIEW

**Comment by vkynchev** [comment]
@vagabondan What has to be clarified? I'm online right now...

**Comment by vagabondan** [comment]
@vkynchev I've got some exceptions after trying to implement your changes. I need some time to figure out the reason and fix them. You did great job and I don't want to miss your contribution so I've included your changes at separate branch dev.users for now and plan to merge it with develop some later.
I've rebuilt MySQL DB from migration manager but still have following exceptions:

```
21:35:14 [Error] [CoiniumServ.Persistance.Layers.Hybrid.HybridStorage] [Litecoin] InvalidOperationException while GetBlocks
System.InvalidOperationException: A parameterless default constructor or one matching signature (System.Int32 Height, System.Boolean Orphaned, System.Boolean Confirmed, System.Boolean Accounted, System.String BlockHash, System.String TxHash, System.Decimal Amount, System.Boolean Reward, System.DateTime CreatedAt) is required for CoiniumServ.Persistance.Blocks.PersistedBlock materialization
  at Dapper.SqlMapper.GetTypeDeserializerImpl (System.Type type, System.Data.IDataReader reader, System.Int32 startBound, System.Int32 length, System.Boolean returnNullIfFirstMissing) [0x00280] in <c2d1885bdc7347758e84aae52723b0b3>:0 
  at Dapper.SqlMapper+TypeDeserializerCache.GetReader (System.Data.IDataReader reader, System.Int32 startBound, System.Int32 length, System.Boolean returnNullIfFirstMissing) [0x00062] in <c2d1885bdc7347758e84aae52723b0b3>:0 
  at Dapper.SqlMapper+TypeDeserializerCache.GetReader (System.Type type, System.Data.IDataReader reader, System.Int32 startBound, System.Int32 length, System.Boolean returnNullIfFirstMissing) [0x00057] in <c2d1885bdc7347758e84aae52723b0b3>:0 
  at Dapper.SqlMapper.GetTypeDeserializer (System.Type type, System.Data.IDataReader reader, System.Int32 startBound, System.Int32 length, System.Boolean returnNullIfFirstMissing) [0x00000] in <c2d1885bdc7347758e84aae52723b0b3>:0 
  at Dapper.SqlMapper.GetDeserializer (System.Type type, System.Data.IDataReader reader, System.Int32 startBound, System.Int32 length, System.Boolean returnNullIfFirstMissing) [0x00090] in <c2d1885bdc7347758e84aae52723b0b3>:0 
  at Dapper.SqlMapper+<QueryImpl>d__125`1[T].MoveNext () [0x00137] in <c2d1885bdc7347758e84aae52723b0b3>:0 
  at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00077] in /run/build/mono/mcs/class/referencesource/mscorlib/system/collections/generic/list.cs:99 
  at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00015] in /run/build/mono/external/corefx/src/System.Linq/src/System/Linq/ToCollection.cs:30 
  at Dapper.SqlMapper.Query[T] (System.Data.IDbConnection cnn, System.String sql, System.Object param, System.Data.IDbTransaction transaction, System.Boolean buffered, System.Nullable`1[T] commandTimeout, System.Nullable`1[T] commandType) [0x0003c] in <c2d1885bdc7347758e84aae52723b0b3>:0 
  at CoiniumServ.Persistance.Layers.Hybrid.HybridStorage.GetBlocks (CoiniumServ.Persistance.Query.IPaginationQuery paginationQuery) [0x0002e] in /home/strannix/structure/CoiniumServ/src/CoiniumServ/Persistance/Layers/Hybrid/HybridStorage.Blocks.cs:136 
21:35:14 [Error] [CoiniumServ.Pools.PoolManager] [global] Error recaching statistics; "Value cannot be null.\nParameter name: collection"
```


-----------------------

```
21:35:15 [Error] [CoiniumServ.Persistance.Layers.Hybrid.HybridStorage] [Litecoin] InvalidOperationException while GetAccountByUsername
System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.Single[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00028] in /run/build/mono/external/corefx/src/System.Linq/src/System/Linq/Single.cs:23 
  at CoiniumServ.Persistance.Layers.Hybrid.HybridStorage.GetAccountByUsername (System.String username) [0x00028] in /home/strannix/structure/CoiniumServ/src/CoiniumServ/Persistance/Layers/Hybrid/HybridStorage.Accounts.cs:74
```

**Comment by vkynchev** [comment]
@vagabondan Could you try to use my branch (in a separate directory) `develop-vkynchev` and post if it works? However It's very strange - it works perfectly on my machine... If you are setting up the project from the ground up you need to copy the `/src/CoiniumServ/config` dir to the `/bin/Debug` folder... The migrations work too...

**Comment by vkynchev** [comment]
@vagabondan About the second error - there has to be something in redis... check the shares for the current round... Delete redis' data and try again... When migrating you are migrating only MySQL, but there are still old records in redis.

**Comment by vagabondan** [comment]
@vkynchev let's move to new Issue https://github.com/vagabondan/CoiniumServ/issues/14
Or we can easilly loose this conversation.

**Pull request merged**
